base-url:
  host: http://127.0.0.1:9091/mp/enclosure

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 1024KB
      location: C:/upload
      max-file-size: 1024MB
      max-request-size: 1024MB